### ISSUE TITLE
Enhancement: option to not concat/uglify JS files to simplify debugging on-device?

### ISSUE THREAD

**Issue by domhnallw** [tmaximini/generator-ionic-gulp#28]
Hi there:

I'm wondering if it'd be possible to add a switch to the gulpfile templates to facilitate being able to do `gulp -r <platform>` where the the Javascripts in the project are not concatenated or uglified to make debugging a little easier on connected devices?

**Comment by tmaximini** [comment]
not sure if I am able to add this to the generator in near future but you can add it to your project.
in the generated gulpfile, locate this line: https://github.com/tmaximini/generator-ionic-gulp/blob/master/app/templates/_gulpfile.js#L130

as you can see, it always minifies in 'build' mode. maybe you can add another variable (cli param) here https://github.com/tmaximini/generator-ionic-gulp/blob/master/app/templates/_gulpfile.js#L23-L32 in order to supress minification?

**Comment by domhnallw** [comment]
Yep, I've already made that change in my project, thanks. I was just wondering if it could be made an option.

I'll look into it when I get a little more time and see if I can put something together with regards to the CLI parameters to make it a bit slicker, but I'm not an expert in all things gulp.

Thanks for the reply :)
